# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Film Locations' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Film Locations
  pod 'AFNetworking'
  pod 'GoogleMaps'
  pod 'GooglePlaces' 
  pod 'SwiftyJSON', '~>3.1.4'
  pod 'FXBlurView', '~>1.6.4'
  pod 'BDBOAuth1Manager'
  pod 'WCLShineButton'
  pod 'LyftSDK'
  pod 'BRYXBanner'
  pod 'Pastel'
  pod 'Alamofire', '~> 4.4'
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'Fabric'
  pod 'Crashlytics'
end
