# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Film Locations' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Film Locations
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'GoogleMaps', '= 2.1.0'
  pod 'GooglePlaces'
  pod 'AFNetworking'
  pod 'SwiftyJSON', '~>3.1.4'
  pod 'FXBlurView', '~>1.6.4'
  pod 'BDBOAuth1Manager'
  pod 'WCLShineButton'
  pod 'LyftSDK'
end
